name: werewolf_app
description: "This is an app, that should help moderators of the Werewolf game to keep track of the roles, deaths and so on."
publish_to: 'none'

version: 4.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  rename_app: ^1.6.5
  system_theme: ^3.1.2
  easy_localization: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/werwolf-icon.png
    - assets/translations/
