name: werewolve_app
description: "This is an app, that should help moderators of the Werewolve game to keep track of the roles, deaths and so on."
publish_to: 'none'

version: 4.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  rename_app: ^1.6.5
  easy_localization: ^3.0.8
  dynamic_color: ^1.8.1
  shared_preferences: ^2.5.4
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/werwolf-icon.png
    - assets/translations/
  fonts:
    - family: Baloo2
      fonts:
        - asset: assets/fonts/baloo_2_regular.ttf
          weight: 400
        - asset: assets/fonts/baloo_2_medium.ttf
          weight: 500
        - asset: assets/fonts/baloo_2_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/baloo_2_bold.ttf
          weight: 700
        - asset: assets/fonts/baloo_2_extra_bold.ttf
          weight: 800
