name: werewolf_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.1
  rename_app: ^1.6.1
  system_theme: ^3.1.2
  easy_localization: ^3.0.7

flutter_launcher_icons:
  image_path: "assets/icons/werwolf-icon.png"

  android: "launcher_icon"
  # image_path_android: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "assets/icons/werwolf-icon-background.png"
  adaptive_icon_foreground: "assets/icons/werwolf-icon-foreground.png"
  adaptive_icon_monochrome: "assets/icons/werwolf-icon-foreground.png"

  ios: true
  # image_path_ios: "assets/icon/icon.png"
  remove_alpha_channel_ios: true
  image_path_ios_dark_transparent: "assets/icons/werwolf-icon-foreground.png"
  image_path_ios_tinted_grayscale: "assets/icons/werwolf-icon-foreground.png"
  desaturate_tinted_to_grayscale_ios: true

  web:
    generate: true
    image_path: "assets/icons/werwolf-icon-foreground.png"
    background_color: "#000000"
    theme_color: "#2196FF"

  windows:
    generate: true
    image_path: "assets/icons/werwolf-icon-foreground.png"
    icon_size: 48 # min:48, max:256, default: 48

  macos:
    generate: true
    image_path: "assets/icons/werwolf-icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/werwolf-icon.png
    - assets/translations/
